from __future__ import annotations

# Generated from rp.txt. Commands 101–180 already exist in command_catalog.py;
# this file contains the missing moderation aliases 1–100.

EXTRA_MODERATION_COMMANDS = [(1, 'Расенган', 'расенган', 'Перманентный бан (сокрушительный удар)', 'ban', False, 0, None, None, True),
 (2, 'Чидори', 'чидори', 'Бан на 7 дней (пронзающее наказание)', 'ban', False, 604800, None, None, True),
 (3, 'Аматерасу', 'аматерасу', 'Бан навсегда с невозможностью возврата (чёрное пламя)', 'ban', True, 0, None, None, True),
 (4, 'Инфинит цукуёми', 'инфинит_цукуёми', 'Бан всех участников с определённым тегом', 'ban', True, None, None, 'unsupported_mass_tag', False),
 (5, 'Печать проклятия', 'печать_проклятия', 'Бан с пометкой в чёрном списке', 'ban', True, 0, None, 'global_block', True),
 (6, 'Изгнание академии', 'изгнание_академии', 'Бан новичка (ранг генин)', 'ban', False, 0, None, None, True),
 (7, 'Печать пяти элементов', 'печать_пяти_элементов', 'Бан на 30 дней', 'ban', False, 2592000, None, None, True),
 (8, 'Камуй', 'камуй', 'Отправить в другое измерение (бан на 14 дней)', 'ban', False, 1209600, None, None, True),
 (9, 'Ринне тенсей', 'ринне_тенсей', 'Бан с полным удалением сообщений', 'ban', True, 0, 100, 'ban_purge', True),
 (10, 'Муген цукуёми', 'муген_цукуёми', 'Массовый бан по списку', 'ban', True, None, None, 'mass_ban_list', False),
 (11, 'Гендзюцу', 'гендзюцу', 'Мут на 10 минут (иллюзия тишины)', 'mute', False, 600, None, None, True),
 (12, 'Печать молчания', 'печать_молчания', 'Мут на 1 час', 'mute', False, 3600, None, None, True),
 (13, 'Фуин дзюцу', 'фуин_дзюцу', 'Мут на 24 часа (запечатывание голоса)', 'mute', True, 86400, None, None, True),
 (14, 'Шаринган молчания', 'шаринган_молчания', 'Мут на 3 дня', 'mute', True, 259200, None, None, True),
 (15, 'Песок гаары', 'песок_гаары', 'Мут до ручного снятия (засыпать песком)', 'mute', True, 0, None, None, True),
 (16, 'Тень шикамару', 'тень_шикамару', 'Мут на 30 минут (связывание тенью)', 'mute', False, 1800, None, None, True),
 (17, 'Дзюцу паука', 'дзюцу_паука', 'Мут на 6 часов (паутина Кидамару)', 'mute', False, 21600, None, None, True),
 (18, 'Водная тюрьма', 'водная_тюрьма', 'Мут на 12 часов (кисамэ-стайл)', 'mute', False, 43200, None, None, True),
 (19, 'Печать языка', 'печать_языка', 'Запрет на определённые слова', 'lock', True, None, None, 'add_blocked_words', False),
 (20, 'Мудрец молчания', 'мудрец_молчания', 'Мут на 7 дней', 'mute', True, 604800, None, None, True),
 (21, 'Тай дзюцу', 'тай_дзюцу', 'Кик из беседы (удар рукой)', 'kick', False, None, None, None, True),
 (22, 'Листок ураган', 'листок_ураган', 'Кик с предупреждением', 'kick', False, None, None, 'kick_warn', True),
 (23, 'Первичный лотос', 'первичный_лотос', 'Жёсткий кик без предупреждения', 'kick', True, None, None, None, True),
 (24, 'Омо́тэ ренге', 'омо́тэ_ренге', 'Кик с удалением последнего сообщения', 'kick', True, None, None, 'kick_delete', True),
 (25, 'Ура ренге', 'ура_ренге', 'Кик + мут при повторном входе', 'kick', True, None, None, 'kick_reentry_mute', True),
 (26, 'Пинок рока ли', 'пинок_рока_ли', 'Кик за спам', 'kick', False, None, None, None, True),
 (27, 'Сюрикен на выход', 'сюрикен_на_выход', 'Кик с уведомлением', 'kick', False, None, None, None, True),
 (28, 'Клон выгоняет', 'клон_выгоняет', 'Кик всех клонов/альтов пользователя', 'kick', True, None, None, 'unsupported_alts', True),
 (29, 'Свиток изгнания', 'свиток_изгнания', 'Кик с записью в лог', 'kick', False, None, None, None, True),
 (30, 'Ветер выдувания', 'ветер_выдувания', 'Кик за флуд', 'kick', False, None, None, None, True),
 (31, 'Академия предупреждает', 'академия_предупреждает', 'Первое предупреждение', 'warn', False, None, None, None, True),
 (32, 'Генин выговор', 'генин_выговор', 'Второе предупреждение', 'warn', False, None, None, None, True),
 (33, 'Чунин угроза', 'чунин_угроза', 'Третье предупреждение (последнее)', 'warn', False, None, None, None, True),
 (34, 'Джонин гнев', 'джонин_гнев', 'Финальное предупреждение перед баном', 'warn', True, None, None, None, True),
 (35, 'Хокаге ярость', 'хокаге_ярость', 'Ультиматум: бан через 1 минуту', 'warn', True, None, None, 'warn_ban_timer', True),
 (36, 'Анбу наблюдает', 'анбу_наблюдает', 'Скрытое предупреждение (юзер не видит)', 'warn', True, None, None, None, True),
 (37, 'Свиток грехов', 'свиток_грехов', 'Показать все предупреждения юзера', 'warn', False, None, None, 'warns_summary', True),
 (38, 'Печать предупреждения', 'печать_предупреждения', 'Предупреждение с таймером', 'warn', False, None, None, None, True),
 (39, 'Красная печать', 'красная_печать', 'Предупреждение за мат', 'warn', False, None, None, None, True),
 (40, 'Чёрная печать', 'чёрная_печать', 'Предупреждение за оскорбления', 'warn', False, None, None, None, True),
 (41, 'Ринне тенсей кай', 'ринне_тенсей_кай', 'Снять перманентный бан', 'unban', False, None, None, None, True),
 (42, 'Гендзюцу кай', 'гендзюцу_кай', 'Снять мут', 'unmute', False, None, None, None, True),
 (43, 'Печать снята', 'печать_снята', 'Убрать все ограничения', 'unmute', False, None, None, 'reset_target_restrictions', True),
 (44, 'Возвращение в листок', 'возвращение_в_листок', 'Разбан в беседу', 'unban', False, None, None, None, True),
 (45, 'Мудрец прощает', 'мудрец_прощает', 'Амнистия всех предупреждений', 'unwarn', True, None, None, 'unwarn_all', False),
 (46, 'Воля огня', 'воля_огня', 'Снять бан за хорошее поведение', 'unban', False, None, None, None, True),
 (47, 'Цукуюми отмена', 'цукуюми_отмена', 'Разбан из «измерения»', 'unban', False, None, None, None, True),
 (48, 'Песок отступает', 'песок_отступает', 'Снять бессрочный мут', 'unmute', False, None, None, None, True),
 (49, 'Тень рассеялась', 'тень_рассеялась', 'Снять мут Шикамару', 'unmute', False, None, None, None, True),
 (50, 'Свиток чист', 'свиток_чист', 'Обнулить историю нарушений', 'unwarn', True, None, None, 'clear_user_history', True),
 (51, 'Свиток ниндзя', 'свиток_ниндзя', 'Профиль пользователя в чате', 'lock', False, None, None, 'profile_summary', True),
 (52, 'Ранг ниндзя', 'ранг_ниндзя', 'Показать ранг/роль юзера', 'lock', False, None, None, 'role_summary', True),
 (53, 'Чакра статус', 'чакра_статус', 'Онлайн/оффлайн статус', 'lock', False, None, None, 'presence_summary', True),
 (54, 'Дзюцу лист', 'дзюцу_лист', 'Список активных наказаний', 'lock', False, None, None, 'active_penalties', True),
 (55, 'Академия журнал', 'академия_журнал', 'Лог действий модерации', 'lock', False, None, None, 'logs_summary', False),
 (56, 'Анбу досье', 'анбу_досье', 'Полная история нарушений', 'lock', False, None, None, 'user_history', True),
 (57, 'Свиток правил', 'свиток_правил', 'Показать правила беседы', 'lock', False, None, None, 'rules_summary', False),
 (58, 'Карта деревни', 'карта_деревни', 'Список участников', 'lock', False, None, None, 'members_summary', False),
 (59, 'Совет пяти каге', 'совет_пяти_каге', 'Список модераторов', 'lock', False, None, None, 'call_moderators', False),
 (60, 'Миссия ранг S', 'миссия_ранг_S', 'Показать самые серьёзные нарушения', 'lock', True, None, None, 'serious_violations', True),
 (61, 'Назначить генин', 'назначить_генин', 'Дать ранг новичка', 'lock', False, None, None, 'set_role', True),
 (62, 'Назначить чунин', 'назначить_чунин', 'Дать ранг участника', 'lock', False, None, None, 'set_role', True),
 (63, 'Назначить джонин', 'назначить_джонин', 'Дать ранг модератора', 'lock', True, None, None, 'set_role', True),
 (64, 'Назначить хокаге', 'назначить_хокаге', 'Дать ранг админа', 'lock', True, None, None, 'set_role', True),
 (65, 'Назначить анбу', 'назначить_анбу', 'Дать скрытый ранг модератора', 'lock', True, None, None, 'set_role', True),
 (66, 'Назначить саннин', 'назначить_саннин', 'Дать VIP-статус', 'lock', True, None, None, 'set_role', True),
 (67, 'Назначить акуцуки', 'назначить_акуцуки', 'Метка «под наблюдением»', 'lock', True, None, None, 'set_role', True),
 (68, 'Назначить каге', 'назначить_каге', 'Дать ранг супермодератора', 'lock', True, None, None, 'set_role', True),
 (69, 'Снять ранг', 'снять_ранг', 'Убрать роль', 'lock', False, None, None, 'remove_role', True),
 (70, 'Экзамен чунин', 'экзамен_чунин', 'Повысить ранг за активность', 'lock', False, None, None, 'promote_activity', True),
 (71, 'Барьер деревни', 'барьер_деревни', 'Закрыть чат для новых', 'lock', True, None, None, 'settings_patch', False),
 (72, 'Барьер снят', 'барьер_снят', 'Открыть чат', 'unlock', False, None, None, None, False),
 (73, 'Режим войны', 'режим_войны', 'Усилить модерацию (автобан за спам)', 'lock', True, None, None, 'settings_patch', False),
 (74, 'Режим мира', 'режим_мира', 'Ослабить модерацию', 'unlock', False, None, None, 'settings_patch', False),
 (75, 'Четвёртая война', 'четвёртая_война', 'Заблокировать все медиа', 'lock', True, None, None, 'chat_media_lock', False),
 (76, 'Перемирие', 'перемирие', 'Разблокировать медиа', 'unlock', False, None, None, 'chat_media_unlock', False),
 (77, 'Печать чата', 'печать_чата', 'Заморозить чат (никто не пишет)', 'lock', True, None, None, None, False),
 (78, 'Печать снята чат', 'печать_снята_чат', 'Разморозить чат', 'unlock', False, None, None, None, False),
 (79, 'Теневые клоны', 'теневые_клоны', 'Включить антиспам-фильтр', 'lock', False, None, None, 'settings_patch', False),
 (80, 'Бьякуган', 'бьякуган', 'Включить мониторинг всех сообщений', 'lock', True, None, None, 'settings_patch', False),
 (81, 'Сто лет одиночества', 'сто_лет_одиночества', 'Бан на 100 дней', 'ban', True, 8640000, None, None, True),
 (82, 'Бесконечный гендзюцу', 'бесконечный_гендзюцу', 'Мут навсегда', 'mute', True, 0, None, None, True),
 (83, 'Печать орочимару', 'печать_орочимару', 'Запрет на смену ника', 'lock', True, None, None, 'unsupported_nickname_lock', True),
 (84, 'Проклятая метка', 'проклятая_метка', 'Все сообщения юзера помечаются', 'lock', True, None, None, 'mark_dangerous', True),
 (85, 'Свиток запрета', 'свиток_запрета', 'Запрет на использование команд', 'restrict_commands', True, 0, None, None, True),
 (86, 'Тюрьма кири', 'тюрьма_кири', 'Изоляция (видит чат, но не пишет)', 'mute', True, 0, None, None, True),
 (87, 'Испытание иллюзией', 'испытание_иллюзией', 'Капча при каждом сообщении', 'lock', True, None, None, 'captcha_each_message', True),
 (88, 'Печать лимит', 'печать_лимит', 'Ограничение: 3 сообщения в минуту', 'lock', True, None, None, 'restrict_rate', True),
 (89, 'Красный свиток', 'красный_свиток', 'Удалить все сообщения за день', 'purge', True, None, 100, None, False),
 (90, 'Печать забвения', 'печать_забвения', 'Скрыть сообщения юзера от всех', 'mute', True, 0, None, 'unsupported_hide_user', True),
 (91, 'Даттебайо', 'даттебайо', 'Закрепить сообщение', 'lock', False, None, None, 'pin_reply', False),
 (92, 'Расенган очистка', 'расенган_очистка', 'Удалить последние 50 сообщений', 'purge', True, None, 50, None, False),
 (93, 'Каге буншин', 'каге_буншин', 'Создать опрос', 'lock', True, None, None, 'anonymous_poll', False),
 (94, 'Свиток призыва', 'свиток_призыва', 'Пинг конкретного юзера', 'lock', False, None, None, 'ping_target', True),
 (95, 'Собрание каге', 'собрание_каге', 'Пинг всех модераторов', 'lock', False, None, None, 'call_moderators', False),
 (96, 'Миссия ранг D', 'миссия_ранг_D', 'Напомнить о правилах', 'lock', False, None, None, 'rules_summary', False),
 (97, 'Воля огня включена', 'воля_огня_включена', 'Включить приветствие новичков', 'lock', False, None, None, 'settings_patch', False),
 (98, 'Академия выпуск', 'академия_выпуск', 'Поздравление с днём рождения', 'lock', False, None, None, 'birthday_message', True),
 (99, 'Вечный цукуёми', 'вечный_цукуёми', 'Ночной режим чата', 'lock', True, 28800, None, 'night_mode', False),
 (100, 'Седьмой хокаге', 'седьмой_хокаге', 'Команда создателя беседы (полный контроль)', 'lock', True, None, None, 'owner_control_summary', False)]

EXTRA_MODE_PATCHES = {61: {'role': 'member', 'rank_label': 'Генин'},
 62: {'role': 'member', 'rank_label': 'Чунин'},
 63: {'role': 'moderator', 'rank_label': 'Джонин'},
 64: {'role': 'admin', 'rank_label': 'Хокаге', 'owner_only': True},
 65: {'role': 'moderator', 'rank_label': 'АНБУ'},
 66: {'role': 'member', 'rank_label': 'Саннин', 'whitelist': True},
 67: {'role': 'member', 'rank_label': 'Акацуки', 'dangerous': True},
 68: {'role': 'moderator', 'rank_label': 'Каге'},
 71: {'raid_lockdown_enabled': True, 'join_requests_only': True},
 73: {'anti_flood_enabled': True, 'smart_spam_enabled': True, 'duplicate_filter_enabled': True, 'warn_threshold': 2},
 74: {'anti_flood_enabled': True, 'smart_spam_enabled': False, 'duplicate_filter_enabled': False, 'warn_threshold': 5},
 79: {'anti_flood_enabled': True, 'duplicate_filter_enabled': True, 'smart_spam_enabled': True},
 80: {'premium_stats': True, 'reports_enabled': True, 'activity_tracking_enabled': True},
 87: {'captcha_each_message_user_ids': True},
 88: {'per_user_message_limit': 3, 'per_user_message_window_seconds': 60},
 97: {'welcome_enabled': True}}
